const list = [
    {
      id: 1,
      title: "KIDS WEAR TSHIRT",
      author: "BLACK",
      price: 89,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTajv_xroOvZvuuJwhWzbWyA5mPGfVZ9AY_oWl9QNfnemkq58GvWwEVmocwDKmATKUuAm0&usqp=CAU",
      amount: 1,
    },
    {
      id: 2,
      title: "BREAKING BAD T-SHIRT",
      author: "WHITE ",
      price: 98,
      img: "https://www.breakingbadshop.com/wp-content/uploads/2019/10/Promotion-Breaking-Bad-Men-T-Shirts-Retro-T-Shirt-TV-Mr-White-Heisenberg-Jessie-Pinkman-Funny.jpg",
      amount: 1,
    },
    {
      id: 3,
      title: "JESSE PINKMAN",
      author: "CREATIVE",
      price: 143,
      img: "https://cdn11.bigcommerce.com/s-e4notjahj4/images/stencil/1280x1280/products/377/1656/il_fullxfull.1692851076_pl6n__44966.1562576701.jpg?c=2",
      amount: 1,
    },
    {
      id: 4,
      title: "GOT T-SHIRT",
      author: "BLACK",
      price: 57,
      img: "https://roxxbkk.com/wp-content/uploads/2019/04/gamethrones001.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "GOT T-SHIRT",
      author: "COMMENTED",
      price: 149,
      img: "https://ih1.redbubble.net/image.432634733.7663/ssrco,classic_tee,mens,101010:01c5ca27c6,front_alt,square_product,600x600.u1.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "BLUE JEANS",
      author: "CHEAP",
      price: 135,
      img: "https://5.imimg.com/data5/CY/LK/MY-18296/jeans-500x500.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "FRIENDS T-SHIRT ",
      author: "by amazon",
      price: 693,
      img: "https://m.media-amazon.com/images/I/81e3XimH5VL._AC_UL1500_.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "ganges of waseypur tshirt",
      author: "by swagshirt",
      price: 289,
      img: "https://www.swagshirts99.com/wp-content/uploads/2020/10/t8-14.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "ganges of waseypur tshirt ",
      author: "by swagshirt",
      price: 80,
      img: "https://www.swagshirts99.com/wp-content/uploads/2020/10/t3-18.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "red check shirt",
      author: "by decathalon",
      price: 86,
      img: "https://contents.mediadecathlon.com/p1484240/ab565f3675dbdd7e3c486175e2c16583/p1484240.jpg",
      amount: 1,
    },
    {
      id: 11,
      title: "sgirt full sleeve",
      author: "by ajio",
      price: 120,
      img: "https://assets.ajio.com/medias/sys_master/root/20210403/OjjF/6068dc44aeb269a9e33a52ba/-288Wx360H-462103975-pink-MODEL.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "full sleeve shirt",
      author: "by amazon",
      price: 157,
      img: "https://m.media-amazon.com/images/I/319Zx40AhUL.jpg",
      amount: 1,
    },
  ];
  
  export default list;